//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTestPersonSurname
    {
        public string Lang { get; set; }
        public int Id { get; set; }
        public int BaseId { get; set; }
        public string Description { get; set; }
    
        public virtual TestPerson TestPerson { get; set; }
    }
}
