//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.Data.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestPerson()
        {
            this.SubTestPersonDescriptions = new HashSet<SubTestPersonDescription>();
            this.SubTestPersonSurnames = new HashSet<SubTestPersonSurname>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int DescriptionMLId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int SurnameMLId { get; set; }
        public int TestSexId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTestPersonDescription> SubTestPersonDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubTestPersonSurname> SubTestPersonSurnames { get; set; }
        public virtual TestSex TestSex { get; set; }
    }
}
