//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B2B.Data.Resources.DbFields", typeof(DbFields).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWords.
        /// </summary>
        public static string KeyWords {
            get {
                return ResourceManager.GetString("KeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufacturerCode.
        /// </summary>
        public static string ManufacturerCode {
            get {
                return ResourceManager.GetString("ManufacturerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSellCount.
        /// </summary>
        public static string MaxSellCount {
            get {
                return ResourceManager.GetString("MaxSellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeriodOfMaxSellAmount.
        /// </summary>
        public static string PeriodOfMaxSellAmount {
            get {
                return ResourceManager.GetString("PeriodOfMaxSellAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductSpecialist.
        /// </summary>
        public static string ProductSpecialist {
            get {
                return ResourceManager.GetString("ProductSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellIfNotInStock.
        /// </summary>
        public static string SellIfNotInStock {
            get {
                return ResourceManager.GetString("SellIfNotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortDescription.
        /// </summary>
        public static string ShortDescription {
            get {
                return ResourceManager.GetString("ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowInMainPage.
        /// </summary>
        public static string ShowInMainPage {
            get {
                return ResourceManager.GetString("ShowInMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowOrder.
        /// </summary>
        public static string ShowOrder {
            get {
                return ResourceManager.GetString("ShowOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockCode.
        /// </summary>
        public static string StockCode {
            get {
                return ResourceManager.GetString("StockCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockType.
        /// </summary>
        public static string StockType {
            get {
                return ResourceManager.GetString("StockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserComment.
        /// </summary>
        public static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
    }
}
